import { Router } from "express";
import { tenantAuthRoutes } from "../modules/tenant/auth";
import { branchesRoutes } from "../modules/tenant/branches";
import { usersRoutes } from "../modules/tenant/users";
import { permissionsRoutes } from "../modules/tenant/permissions";
import { rolesRoutes } from "../modules/tenant/roles";
import { userRolesRoutes } from "../modules/tenant/roles";
import { settingsRoutes } from "../modules/tenant/settings";
import { tenantCatalogRoutes } from "../modules/tenant/catalog";
import { suppliersRoutes } from "../modules/tenant/suppliers";
import { inventoryRoutes } from "../modules/tenant/inventory";
import { inventoryBatchesRoutes } from "../modules/tenant/inventory-batches";
import { stockMovementsRoutes } from "../modules/tenant/stock-movements";
import { purchasingRoutes } from "../modules/tenant/purchasing";
import { shiftsRoutes } from "../modules/tenant/shifts";
import { posRoutes } from "../modules/tenant/pos";
import { alertsRoutes } from "../modules/tenant/alerts";
import { reportsRoutes } from "../modules/tenant/reports";
import { dashboardRoutes } from "../modules/tenant/dashboard";
import { analyticsRoutes } from "../modules/tenant/analytics";
import { ocrRoutes } from "../modules/tenant/ocr";
import { tenantSupportRoutes } from "../modules/tenant/support";
import { tenantSubscriptionRoutes } from "../modules/tenant/subscription";

const router = Router();

router.use("/auth", tenantAuthRoutes);
router.use("/branches", branchesRoutes);
router.use("/users", usersRoutes);
router.use("/users/:userId/roles", userRolesRoutes);
router.use("/permissions", permissionsRoutes);
router.use("/roles", rolesRoutes);
router.use("/settings", settingsRoutes);
router.use("/catalog", tenantCatalogRoutes);
router.use("/suppliers", suppliersRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/inventory/:itemId/batches", inventoryBatchesRoutes);
router.use("/stock-movements", stockMovementsRoutes);
router.use("/purchasing", purchasingRoutes);
router.use("/shifts", shiftsRoutes);
router.use("/pos", posRoutes);
router.use("/alerts", alertsRoutes);
router.use("/reports", reportsRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/ocr/documents", ocrRoutes);
router.use("/support/tickets", tenantSupportRoutes);
router.use("/subscription", tenantSubscriptionRoutes);

export const tenantRoutes = router;
